# -*- coding: utf-8 -*-
"""Reddit-persona.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZabNGATmzzIwd4javU9zpPQMB1eYXE58
"""

!pip install praw python-dotenv

import praw

client_id = "XJksspIo9onybjJ_oNXTDA"
client_secret = "Fhl...LaAlXw"#my client secret of reddit
user_agent = "PersonaApp/0.1 by kinngofworld"

# Creating Reddit instance
reddit = praw.Reddit(
    client_id=client_id,
    client_secret=client_secret,
    user_agent=user_agent
)

def fetch_user_data(username, limit=100):
    user = reddit.redditor(username)
    posts = []
    comments = []

    try:
        for post in user.submissions.new(limit=limit):
            post_text = f"Title: {post.title}\nBody: {post.selftext}\nURL: {post.url}\n"
            posts.append(post_text)
    except Exception as e:
        print("Error fetching posts:", e)

    try:
        for comment in user.comments.new(limit=limit):
            comment_text = f"Comment: {comment.body}\nSubreddit: {comment.subreddit}\n"
            comments.append(comment_text)
    except Exception as e:
        print("Error fetching comments:", e)

    return posts, comments

username = "kojied"  # Example user
posts, comments = fetch_user_data(username)

print(f"Total Posts: {len(posts)}")
print(f"Total Comments: {len(comments)}")

print("\nSample Post:\n", posts[0][:500])
print("\nSample Comment:\n", comments[0][:500])

all_text = "\n\n".join(posts + comments)  # posts/comments fetched

def build_persona_prompt(username, user_text):
    return f"""
You are an AI profiler. Based on the following Reddit user's posts and comments, generate a detailed user persona.

**Persona should include**:
- Age group
- Likely gender
- Occupation or field
- Hobbies/interests
- Writing style or tone
- Subreddits they frequent
- Possible location or background
- Notable beliefs or opinions

**Important**: After each trait, cite the exact post or comment (or quote a line) that helped you decide it.

### Reddit User: {username}
### Posts & Comments:
{user_text}
"""

from openai import OpenAI

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key="sk-or-v1-499e....c5372a26c"  #MY DEEPSEEK R1 API KEY
)

def generate_persona_openrouter(prompt):
    completion = client.chat.completions.create(
        model="deepseek/deepseek-r1:free",
        messages=[
            {"role": "user", "content": prompt}
        ],
        extra_headers={
            "HTTP-Referer": "https://github.com/Abhiudai12",
        }
    )
    return completion.choices[0].message.content

username = "Hungry-Move-6603"
user_text = "\n\n".join(posts + comments)
prompt = build_persona_prompt(username, user_text)
persona = generate_persona_openrouter(prompt)

print(persona)

with open("Hungry-Move-6603.txt", "w", encoding="utf-8") as f:
    f.write(persona)